-- !Ups
ALTER TYPE TRADING_PAIR ADD VALUE 'BTC_ETH';
ALTER TYPE TRADING_PAIR ADD VALUE 'BTC_USDC';
ALTER TYPE TRADING_PAIR ADD VALUE 'ETH_USDC';

ALTER TYPE CURRENCY_TYPE ADD VALUE 'ETH';
ALTER TYPE CURRENCY_TYPE ADD VALUE 'USDC';
